### PR TITLE
Let users choose channel to chat in with engine.chat()

### PR DESCRIPTION
**Pull request by Empty2k12**
This pull request adds a second parameter to engine.chat(): The channel.

This code is untested. Please use with caution!

### CODE REVIEW

**Comment by CoreCompetency** [comment]
Is there a way to chat to a specific channel without this?  Is it possible to use engine.getEngine().ws somehow?  Emit doesn't fail but doesn't seem to do anything.

**Comment by kungfuant** [comment]
@CoreCompetency Yes there is. engine.getEngine() only gives you access to game related functions (betting, cashing out, playerlist, aso) but no chat related functionality. Unfortunately the chat engine is not exposed, so you have to access the global instance by importing the 'game-logic/ChatEngineStore' module.

**Comment by kungfuant** [comment]
Also note this is for babv1 only. I never looked at how babv2 does scripts.

**Comment by CoreCompetency** [comment]
@kungfuant Can that be done on the client side?  I'm trying to figure out how to target a specific channel with a script that's running for a player.

**Pull request closed without merging**
